# 데이터분석을 위한 패키지

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
arr1 = np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 = np.array([0.1, 0.2, 0.3])
arr2

array([0.1, 0.2, 0.3])

In [6]:
arr3 = np.array(['a', 'b', 'c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [7]:
arr4 = np.array([1, 2, 'a', 'b', 0.1, 0.2])
arr4

array(['1', '2', 'a', 'b', '0.1', '0.2'], dtype='<U11')

In [9]:
arr5 = np.array([1, 2, 0.3, 0.4])   # => 결과를 보면 다 실수형으로 통일됨!!
arr5

array([1. , 2. , 0.3, 0.4])

In [10]:
arr6 = np.array(    # => n차원 배열을 알아서 인식한다.
    [[1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9]]
)
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr7 = np.array(    # => n차원 배열을 알아서 인식한다.
    [[1, 2, 3, 0],
    [4, 5, 6, 0], 
    [7, 8, 9, 0]]
)
arr7

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

## array 타입
- list 는 다양한 형태의 요소가 들어올 수 있다.
- array 는 요소의 데이터 타입이 반드시 통일돼서 저장이 된다!!!!

In [8]:
l1 = [1, 0.1, 'a', 'b', [2, 3, 4]]
l1

[1, 0.1, 'a', 'b', [2, 3, 4]]

In [20]:
print(arr1.dtype)
arr1

int32


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(arr2.dtype)
arr2

float64


array([0.1, 0.2, 0.3])

In [22]:
print(arr3.dtype)
arr3

<U1


array(['a', 'b', 'c'], dtype='<U1')

In [23]:
print(arr4.dtype)
arr4

<U11


array(['1', '2', 'a', 'b', '0.1', '0.2'], dtype='<U11')

In [24]:
print(arr5.dtype)
arr5

float64


array([1. , 2. , 0.3, 0.4])

## shape

In [25]:
arr5

array([1. , 2. , 0.3, 0.4])

In [26]:
arr5.shape

(4,)

In [27]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr6.shape

(3, 3)

In [30]:
arr7

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

In [31]:
arr7.shape

(3, 4)

## arange

In [32]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr2 = np.arange(3, 13)
arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
arr3 = np.arange(5.0)
arr3

array([0., 1., 2., 3., 4.])

In [35]:
arr4 = np.arange(3, 100, 3.0)
arr4

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39.,
       42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75., 78.,
       81., 84., 87., 90., 93., 96., 99.])

## linspace
- 구간을 균등하게 나눠줌

In [38]:
np.linspace(-5, 5, 10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

## reshape (배열의 형태 변환)

In [45]:
# 1 dimension
arr = np.arange(36.0)
print(arr.shape)
arr

(36,)


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [44]:
# 2 dimension
arr2 = arr.reshape(12, 3)
print(arr2.shape)
arr2

(12, 3)


array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.],
       [30., 31., 32.],
       [33., 34., 35.]])

In [43]:
# 3 dimension
arr3 = arr.reshape(3, 4, 3)
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [47]:
print(arr1.shape)
arr1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr1.shape = (5, 2)   # 권장하지 않는 방법
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [49]:
# -1 shape
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [52]:
arr3.reshape(-1, 12)   ## (3, 12) 로 바꿔준다  => 나는 12만 결정할게 , -1은 너가 자동으로 넣어줘 라는 뜻

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.]])

In [53]:
arr3.reshape(4, -1, 3)

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]],

       [[27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

## astype - 배열의 dtype 변환

In [54]:
arr1 = np.arange(5)
arr2 = np.arange(0.0, 0.5, 0.1)
arr1, arr2

(array([0, 1, 2, 3, 4]), array([0. , 0.1, 0.2, 0.3, 0.4]))

In [55]:
print(arr1.dtype)
print(arr2.dtype)

int32
float64


In [58]:
# int -> float
print(arr1.astype(float))
print(arr1.astype(np.float64))   ## 이게 더 보편적인 방법!!

[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]


In [59]:
# float -> char
print(arr1.astype(str))
print(arr1.astype(np.str))   ## 이게 더 보편적인 방법!!

['0' '1' '2' '3' '4']
['0' '1' '2' '3' '4']


## random

### rand

In [60]:
np.random.rand(5)

array([0.30678042, 0.43814737, 0.36940449, 0.20174044, 0.21495427])

In [61]:
np.random.rand(3,3)

array([[0.1249548 , 0.99522719, 0.6838764 ],
       [0.88961507, 0.75031761, 0.82830154],
       [0.12017426, 0.35041193, 0.673651  ]])

In [62]:
np.random.rand(2,2,2)

array([[[0.31473516, 0.13376054],
        [0.22691119, 0.10432236]],

       [[0.42409568, 0.98304143],
        [0.56940609, 0.8462265 ]]])

### randint

In [63]:
np.random.randint(-5, 3, (3, 3))   ## -5에서 3까지 (3,3)shape으로 뽑겠다.

array([[-2,  2, -4],
       [-3, -1, -1],
       [ 2, -2, -5]])

### randn

In [66]:
np.random.randn(2, 5)   ## (2, 5) 형태로 0에서 1까지의 소수 난수를 뽑겠다.

array([[-1.07736456, -0.31040516,  0.00472331,  0.09492152, -0.83136231],
       [ 0.37059779,  0.60331422, -1.84711509,  0.84174057,  1.22313969]])

## array의 indexing, slicing

In [68]:
arr1 = np.arange(0, 100, 10.0)
arr1

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [70]:
arr1[0], arr1[-1], arr1[5]

(0.0, 90.0, 50.0)

In [71]:
arr1[:], arr1[4:], arr1[1:8]

(array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]),
 array([40., 50., 60., 70., 80., 90.]),
 array([10., 20., 30., 40., 50., 60., 70.]))

In [72]:
arr1[::2], arr1[::3]

(array([ 0., 20., 40., 60., 80.]), array([ 0., 30., 60., 90.]))

## n-Dim Array Indexing, Slicing

In [73]:
# 2 차원 배열 : 0 ~ 23 까지 차례로 (8, 3) 의 배열을 만드시오. dtype = float
arr2 = np.arange(24.0).reshape(8, 3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [75]:
arr2[0], arr[4]

(array([0., 1., 2.]), 4.0)

In [78]:
print(arr2[3][1])   ### 성능이 조금 느리다!
print(arr2[3, 1])   ### 더 좋은 방법

10.0
10.0


In [82]:
print(arr2[3, 1:])
print(arr2[3:, 1:])
print(arr2[::2, :])

[10. 11.]
[[10. 11.]
 [13. 14.]
 [16. 17.]
 [19. 20.]
 [22. 23.]]
[[ 0.  1.  2.]
 [ 6.  7.  8.]
 [12. 13. 14.]
 [18. 19. 20.]]


In [88]:
print(arr2[[0, 5, 3]])
print('-' * 10)
print(arr2[[0, 5, 3], [1]])
print('-' * 10)
print(
    arr2[
        [0, 5, 3]
    ]
)

[[ 0.  1.  2.]
 [15. 16. 17.]
 [ 9. 10. 11.]]
----------
[ 1. 16. 10.]
----------
[[ 0.  1.  2.]
 [15. 16. 17.]
 [ 9. 10. 11.]]


In [91]:
arr2[arr2 > 10]

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [92]:
arr2 > 10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [93]:
arr2[arr2 % 2 == 1]

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

## numpy 의 상수

In [96]:
arr = np.array([1, 2, 3, np.nan, np.inf, -np.inf])    ## nan : 숫자가 아님 (결측치)
print("dtype : ", arr.dtype)
arr

dtype :  float64


array([  1.,   2.,   3.,  nan,  inf, -inf])

## arr 의 연산

In [98]:
arr1 = np.arange(0, 10, 1)
arr2 = np.arange(1, 0, -0.1)
arr1, arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [101]:
# array 와 scalar 연산
arr1 + 1
arr1 + [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
print(arr1 - 1)
print(arr1 * 10)
print(arr1 / 10)
print(arr1 ** 2)
print(arr1 % 2)

[-1  0  1  2  3  4  5  6  7  8]
[ 0 10 20 30 40 50 60 70 80 90]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]


In [103]:
arr1, arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [104]:
arr1 + arr2

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [105]:
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)
print(arr1 % arr2)

[-1.   0.1  1.2  2.3  3.4  4.5  5.6  6.7  7.8  8.9]
[0.  0.9 1.6 2.1 2.4 2.5 2.4 2.1 1.6 0.9]
[ 0.          1.11111111  2.5         4.28571429  6.66666667 10.
 15.         23.33333333 40.         90.        ]
[0.         1.         1.74110113 2.15766928 2.29739671 2.23606798
 2.04767251 1.79278996 1.51571657 1.24573094]
[0.  0.1 0.4 0.2 0.4 0.5 0.4 0.1 0.2 0.1]


In [106]:
arr1 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [107]:
arr1 > arr2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## 행렬

### 0행렬

In [109]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [111]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 1행렬

In [112]:
np.ones(3)

array([1., 1., 1.])

In [113]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 단위행렬

In [114]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [115]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [116]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [117]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 통계를 위한 연산

In [119]:
arr1 = np.arange(1, 11.0).reshape(5, 2)
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

### sum

In [120]:
arr1.sum()

55.0

In [122]:
arr1.sum(axis = 0)

array([25., 30.])

In [123]:
arr1.sum(axis = 1)

array([ 3.,  7., 11., 15., 19.])

### mean

In [124]:
arr1.mean()

5.5

In [126]:
arr1.mean(axis = 0)

array([5., 6.])

In [127]:
arr1.mean(axis = 1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

## var

In [128]:
arr1.var()

8.25

In [129]:
arr1.var(axis = 0)

array([8., 8.])

In [130]:
arr1.var(axis = 1)

array([0.25, 0.25, 0.25, 0.25, 0.25])

## std

In [131]:
arr1.std()

2.8722813232690143

In [132]:
arr1.std(axis = 0)

array([2.82842712, 2.82842712])

In [133]:
arr1.std(axis = 1)

array([0.5, 0.5, 0.5, 0.5, 0.5])

### min

In [143]:
print(arr1.min())
print(arr1.min(axis = 0))
print(arr1.min(axis = 1))

1.0
[1. 2.]
[1. 3. 5. 7. 9.]


### max

In [144]:
print(arr1.max())
print(arr1.max(axis = 0))
print(arr1.max(axis = 1))

10.0
[ 9. 10.]
[ 2.  4.  6.  8. 10.]


### cumsum (누적합)

In [147]:
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [145]:
print(arr1.cumsum())
print(arr1.cumsum(axis = 0))
print(arr1.cumsum(axis = 1))

[ 1.  3.  6. 10. 15. 21. 28. 36. 45. 55.]
[[ 1.  2.]
 [ 4.  6.]
 [ 9. 12.]
 [16. 20.]
 [25. 30.]]
[[ 1.  3.]
 [ 3.  7.]
 [ 5. 11.]
 [ 7. 15.]
 [ 9. 19.]]


### cumprod (누적곱)

In [148]:
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [146]:
print(arr1.cumprod())
print(arr1.cumprod(axis = 0))
print(arr1.cumprod(axis = 1))

[1.0000e+00 2.0000e+00 6.0000e+00 2.4000e+01 1.2000e+02 7.2000e+02
 5.0400e+03 4.0320e+04 3.6288e+05 3.6288e+06]
[[1.00e+00 2.00e+00]
 [3.00e+00 8.00e+00]
 [1.50e+01 4.80e+01]
 [1.05e+02 3.84e+02]
 [9.45e+02 3.84e+03]]
[[ 1.  2.]
 [ 3. 12.]
 [ 5. 30.]
 [ 7. 56.]
 [ 9. 90.]]


### sqrt, log, exp

In [134]:
np.sqrt(arr1.var(axis = 1))

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [136]:
np.log(arr1)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947],
       [1.94591015, 2.07944154],
       [2.19722458, 2.30258509]])

In [138]:
print(np.exp(arr1).dtype)
np.exp(arr1)

float64


array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04]])

In [139]:
2.5e+3

2500.0

In [140]:
2.5e-2

0.025

## 행렬 연산

In [149]:
arr1 = np.arange(1, 7).astype(np.float64).reshape(2, 3)
arr2 = np.arange(6, 0, -1.0).astype(np.float64).reshape(3, 2)
arr1, arr2

(array([[1., 2., 3.],
        [4., 5., 6.]]), array([[6., 5.],
        [4., 3.],
        [2., 1.]]))

In [151]:
arr1.shape, arr2.shape

((2, 3), (3, 2))

In [152]:
arr1 @ arr2

array([[20., 14.],
       [56., 41.]])

In [153]:
arr1.dot(arr2)

array([[20., 14.],
       [56., 41.]])

In [154]:
np.matmul(arr1, arr2)

array([[20., 14.],
       [56., 41.]])

### 전치

In [155]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [157]:
arr3 = np.random.rand(3, 1) * 10
arr3

array([[1.71137577],
       [3.64153251],
       [9.34229129]])

In [160]:
arr1.shape, arr3.shape

((2, 3), (2, 3))

In [161]:
arr3.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [159]:
arr3 = np.arange(6).reshape(2, 3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [162]:
arr1.dot(arr3.T)

array([[ 8., 26.],
       [17., 62.]])

In [163]:
arr1 = np.arange(1, 5).reshape(2, 2)
arr1

array([[1, 2],
       [3, 4]])

In [164]:
np.linalg.inv(arr1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### 역행렬

In [168]:
arr1 = np.arange(1, 5).reshape(2, 2)
arr1

array([[1, 2],
       [3, 4]])

In [169]:
arr2 = np.linalg.inv(arr1)
arr2

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [170]:
arr1.dot(arr2)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [171]:
arr2.dot(arr1)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

### concat

In [173]:
arr1 = np.arange(4).reshape(2, 2)
arr2 = np.arange(0, 40, 10).reshape(2, 2)
arr1, arr2

(array([[0, 1],
        [2, 3]]), array([[ 0, 10],
        [20, 30]]))

In [174]:
np.concatenate((arr1, arr2), axis = 0)

array([[ 0,  1],
       [ 2,  3],
       [ 0, 10],
       [20, 30]])

In [175]:
np.concatenate((arr1, arr2), axis = 1)

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

In [176]:
# np.c_
np.c_[arr1, arr2]

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

# numpy 연습문제

### #1

In [183]:
# 1
arr1 = np.zeros(10)
arr1[3] = 1
arr1[4] = 1
arr1 = arr1.reshape(5, 2)
arr1

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.]])

### #2

In [196]:
# 2
arr2 = np.arange(10, 30, 2)
a = [1., 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]

print(arr2 + a)
print(arr2 - a)
print(arr2 * a)
print(arr2 / a)

[11.  13.1 15.2 17.3 19.4 21.5 23.6 25.7 27.8 29.9]
[ 9.  10.9 12.8 14.7 16.6 18.5 20.4 22.3 24.2 26.1]
[10.  13.2 16.8 20.8 25.2 30.  35.2 40.8 46.8 53.2]
[10.         10.90909091 11.66666667 12.30769231 12.85714286 13.33333333
 13.75       14.11764706 14.44444444 14.73684211]


### #3

In [193]:
# 3
arr3 = np.linspace(1, 101, 10)

print(arr3.sum())
print(arr3.mean())
print(arr3.std())
print(arr3.var())
print(arr3.min())
print(arr3.max())
print(arr3.cumsum())
print(arr3.cumprod())

510.0
51.0
31.91423692521127
1018.5185185185185
1.0
101.0
[  1.          13.11111111  36.33333333  70.66666667 116.11111111
 172.66666667 240.33333333 319.11111111 409.         510.        ]
[1.00000000e+00 1.21111111e+01 2.81246914e+02 9.65614403e+03
 4.38818101e+05 2.48176015e+07 1.67932437e+09 1.32293442e+11
 1.18917105e+13 1.20106276e+15]


### #4

In [219]:
# 4
np.random.seed(42)   ## 랜덤값을 고정시켜준다.
arr4 = np.random.randint(0, 11, (3, 3))
arr4

array([[ 6,  3, 10],
       [ 7,  4,  6],
       [ 9,  2,  6]])

### #5

In [203]:
# 5
arr4 = np.random.randint(0, 11, (3, 3))
arr5 = arr4.astype(np.float64)
arr5

array([[ 8.,  9.,  6.],
       [10.,  4.,  9.],
       [ 0.,  1.,  2.]])

### #6

In [223]:
# 강사님
arr1 = np.linspace(-1000, 1000, 5)
arr1 = arr1.reshape(5, -1)

arr2 = np.linspace(0, 10, 5)
arr2 = arr2.reshape(5, -1)

arr3 = np.concatenate((arr1, arr2), axis = 1)
arr3

array([[-1000. ,     0. ],
       [ -500. ,     2.5],
       [    0. ,     5. ],
       [  500. ,     7.5],
       [ 1000. ,    10. ]])

In [220]:
# 나
arr6 = np.arange(10).reshape(5, 2)
print(arr6)
(arr6 - arr6.mean(axis = 0)) / arr6.std(axis = 0)   ## 표준정규화 : 평균 = 0, 분산 = 1

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([[-1.41421356, -1.41421356],
       [-0.70710678, -0.70710678],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356]])

### #7

In [224]:
# 7
arr7 = np.arange(10).reshape(5, 2)
print(arr7)
(arr7 - arr7.min(axis = 0)) / (arr7.max(axis = 0) - arr7.min(axis = 0))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])