# 폐암 수술 환자의 생존율 예측하기

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.0.0


In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

import numpy as np
import tensorflow as tf

In [5]:
# 실행할 때마다 같은 결과를 출력하기 위해 설정하는 부분입니다.
np.random.seed(3)
tf.random.set_seed(3)

In [8]:
Data_set = np.loadtxt("ThoraricSurgery.csv", delimiter = ",")

In [9]:
# 환자의 기록과 수술 결과를 X와 Y로 구분하여 저장합니다.
X = Data_set[:,0:17]
Y = Data_set[:, 17]

# 딥러닝 구조를 결정합니다.(모델을 설정하고 실행하는 부분입니다.)
model = Sequential()
model.add(Dense(30, input_dim = 17, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

# 딥러닝을 실행합니다.
model.compile(loss = 'mean_squared_error', optimizer = 'adam', metrics = ['accuracy'])
model.fit(X, Y, epochs = 100, batch_size = 10)

# 결과를 출력합니다.
print("\n Accuracy : %.4f" % (model.evaluate(X, Y)[1]))

Train on 470 samples
Epoch 1/100
470/470 [==============================] - 1s 2ms/sample - loss: 0.1495 - accuracy: 0.8404
Epoch 2/100
470/470 [==============================] - 0s 91us/sample - loss: 0.1447 - accuracy: 0.8511
Epoch 3/100
470/470 [==============================] - 0s 99us/sample - loss: 0.1448 - accuracy: 0.8511
Epoch 4/100
470/470 [==============================] - 0s 97us/sample - loss: 0.1453 - accuracy: 0.8489
Epoch 5/100
470/470 [==============================] - 0s 99us/sample - loss: 0.1438 - accuracy: 0.8511
Epoch 6/100
470/470 [==============================] - 0s 102us/sample - loss: 0.1419 - accuracy: 0.8511
Epoch 7/100
470/470 [==============================] - 0s 99us/sample - loss: 0.1425 - accuracy: 0.8511
Epoch 8/100
470/470 [==============================] - 0s 100us/sample - loss: 0.1427 - accuracy: 0.8468
Epoch 9/100
470/470 [==============================] - 0s 96us/sample - loss: 0.1446 - accuracy: 0.8489
Epoch 10/100
470/470 [====================


 Accuracy : 0.8553


# Numpy

In [2]:
import numpy as np

In [15]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])

In [16]:
type(ar)

numpy.ndarray

In [18]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80]])
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [21]:
arr[1, 2]

70

In [20]:
arr[-1,-1]

80

In [26]:
arr[0,]

array([10, 20, 30, 40])

In [27]:
arr[0]

array([10, 20, 30, 40])

In [29]:
arr[:,0]

array([10, 50])

In [31]:
m = np.array([[0,1,2,3,4],
             [5,6,7,8,9],
             [10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
print(m[1,2])
print(m[-1,-1])
print(m[1, 1:3])
print(m[1:3, 2])
print(m[:2,3:5])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [38]:
a = np.array([0,1,2,3])
idx = np.array([True, False, True, False])

a[idx]

array([0, 2])

In [39]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [41]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [45]:
x = np.array(['a', 'b', 'cd'])
x.dtype

dtype('<U2')

In [3]:
X = np.array([[1, 2, 3],
            [4, 5, 6]])
Y = np.array([[10, 20, 30],
            [40, 50, 60]])

In [4]:
X * Y   ## 각각의 곱

array([[ 10,  40,  90],
       [160, 250, 360]])

In [5]:
np.dot(X, Y)  ## 행렬 곱 => 차원 에러

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [6]:
np.dot(X, Y.T)

array([[140, 320],
       [320, 770]])

In [9]:
a = np.array([[4,2,3],
              [4,1,6],
              [7,8,3]])
np.sort(a)    ## defalt : axis = 1

array([[2, 3, 4],
       [1, 4, 6],
       [3, 7, 8]])

In [11]:
np.sort(a, axis = 0)

array([[4, 1, 3],
       [4, 2, 3],
       [7, 8, 6]])